server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://139.196.139.1:3306/emall?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # url: jdbc:mysql://localhost:3306/emall?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: hive
    password: hive
    driver-class-name: com.mysql.cj.jdbc.Driver
# spring:
#   datasource:
#       url: jdbc:hive2://139.196.139.1:10000/emall
#       username: hive
#       password: hive
#       driver-class-name: org.apache.hive.jdbc.HiveDriver
#       type: com.alibaba.druid.pool.DruidDataSource
